modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "LGPL-3.0-or-later"

[[mods]]
modId = "langpatchconf"
version = "${version}"
displayName = "Enchantment Level Language Patch Config"
authors = "teddyxlandlee"
description = '''
Config extension for Enchlevel-LangPatch
'''
logoFile = "935d03af-fa71-4839-a8ac-10d52360807a.png"

[[dependencies.langpatchconf]]
modId = "neoforge"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.langpatchconf]]
modId = "enchlevellangpatch"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"
